/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function GrowingPlant(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Growing Plant in Pot.glb')
  return (
    <group ref={group} {...props} dispose={null} scale={0.2} position={[0, 0.2, 0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Cylinder-Mesh'].geometry}
        material={materials['Material.001']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Cylinder-Mesh_1'].geometry}
        material={materials['Material.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={nodes.Cylinder001.material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={nodes.Cylinder002.material}
      />
    </group>
  )
}

useGLTF.preload('/Growing Plant in Pot.glb')