/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Tree(props) {
  const position = (props.position ? props.position : [0, 0, 0]);
  position[1] += 1;
  const group = useRef()
  const { nodes, materials } = useGLTF('/cypress tree.glb')
  return (
    <group ref={group} {...props} dispose={null} scale={20} position={position}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Node-Mesh'].geometry}
        material={materials.mat9}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Node-Mesh_1'].geometry}
        material={materials.mat19}
      />
    </group>
  )
}

useGLTF.preload('/cypress tree.glb')